version: '3.7'
services:
  web:
    build: .
    image: mydjango
    container_name: mydjango_web
    volumes:
      - ./mydjango:/src
    ports:
      - '8888:8000'
    networks:
      - backend

networks:
  backend:

volumes:
  mydjango:

