version: '2'  
services:  
  nginx:
    image: nginx:alpine
    container_name: nginx_c
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    iamge: django-docker-web
    container_name: web_c
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
  db:
    image: postgres:alpine
    container_name: postgres_c
  redis:
    image: redis:alpine
    container_name: redis_c
    ports:
     - '6377:6379'
